# Generated by Django 5.0.2 on 2025-11-21 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administradores',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='alumnos',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='maestros',
            options={'verbose_name': 'Maestro', 'verbose_name_plural': 'Maestros'},
        ),
    ]
