# Generated by Django 5.0.2 on 2025-12-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0005_eventoacademico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoacademico',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
